version: '3.9'

services:
    db:
        image: postgres:17.0
        restart: always

        # set shared memory limit when using docker-compose
        # shm_size: 128mb
        # or set shared memory limit when deploy via swarm stack
        ports:
            - '5432:5432'
        # volumes:
        #     - moon-data:/var/lib/postgresql/data
        #  - type: tmpfs
        #    target: /dev/shm
        #    tmpfs:
        #      size: 134217728 # 128*2^20 bytes = 128Mb
        environment:
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
# volumes:
#     moon-data:
